name = "CodexMach"
uuid = "dbf7be03-f09c-4874-9d54-616eaa9cc35e"
authors = ["Michael Schlottke-Lakemper <michael.schlottke-lakemper@uni-a.de>"]
version = "0.1.0"

[deps]
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[extras]
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[extensions]
CodexMachCUDAExt = "CUDA"
CodexMachMetalExt = "Metal"

[compat]
KernelAbstractions = "0.9.38"
CUDA = "5"
Metal = "1"
Plots = "1.41.1"
TimerOutputs = "0.5.29"
julia = "1.11"
