name = "CodexMach"
uuid = "dbf7be03-f09c-4874-9d54-616eaa9cc35e"
authors = ["Michael Schlottke-Lakemper <michael.schlottke-lakemper@uni-a.de>"]
version = "0.1.0"

[deps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
Plots = "1.41.1"
TimerOutputs = "0.5.29"
julia = "1.11"
