name: CI

on:
  push:
    branches: ["main", "master"]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ["1"]
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: artifacts-${{ runner.os }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            artifacts-${{ runner.os }}-
      - name: Instantiate dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Run tests with coverage
        run: julia --project=. -e 'using Pkg; Pkg.test(; coverage=true)'
      - name: Process coverage
        uses: julia-actions/julia-processcoverage@v1
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: lcov.info
          flags: unittests
          fail_ci_if_error: true
