name: Docs

on:
  push:
    branches: ["main", "master"]
  pull_request:

concurrency:
  group: docs-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@v1
        with:
          version: "1"
      - uses: actions/cache@v3
        with:
          path: ~/.julia/artifacts
          key: docs-artifacts-${{ runner.os }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            docs-artifacts-${{ runner.os }}-
      - name: Instantiate package dependencies
        run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - name: Instantiate docs environment
        run: julia --project=docs -e 'using Pkg; Pkg.instantiate()'
      - name: Build documentation
        run: julia --project=docs docs/make.jl
      - name: Upload docs artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs-build
          path: docs/build

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs-build
          path: build
      - name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
